<?php

namespace App\Helpers;

class ConstantHelper
{
    const DEFAULT_PAGE_LIMIT = 30;
    const DEFAULT_DATE_FORMAT = 7;

    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;

    const ADMIN_CODE_PREFIX = 'AD-';
    const STUDENT_CODE_PREFIX = 'ST-';
    const TEACHER_CODE_PREFIX = 'TE-';
    const ROLE_CODE_PREFIX = 'ROLE-';

    const MODULE_CODE_PREFIX = 'MOD-';
    const SERVICE_MODULE_CODE_PREFIX = 'SMOD-';

    const CONTACT_VERIFIED = 1;
    const CONTACT_UNVERIFIED = 0;

    const PAYMENT_STATUS_PENDING = 1;
    const PAYMENT_STATUS_PAID = 2;
    const PAYMENT_STATUS_FAILED = 3;
    const PAYMENT_STATUS_PROCESSING = 4;
    const PAYMENT_STATUS_CASH_PAYMENT = 5;
    const PAYMENT_STATUS_REFUNDED = 6;
    const PAYMENT_STATUS_REFUND_ONLINE_PAYMENT = 7;
    const PAYMENT_STATUS_CASH_PAYMENT_WITH_ONLINE_PAYMENT_PROCESSING = 8;
    const PAYMENT_STATUS_TO_BE_REFUNDED = 9;

    const BOOKING_STATUS_PENDING = 1;
    const BOOKING_STATUS_CONFIRMED = 2;
    const BOOKING_STATUS_BOOKED = 3;
    const BOOKING_STATUS_CANCELLED = 4;
    const BOOKING_STATUS_CANCELLED_WITH_REFUND = 5;
    const BOOKING_STATUS_COMPLETED = 6;
    const BOOKING_STATUS_RESCHEDULED = 7;
    const BOOKING_STATUS_CLOSED = 8;

    const USER_TYPE_ADMIN = 1;
    const USER_TYPE_TEACHER = 2;
    const USER_TYPE_STUDENT = 3;

    const MENU_TYPE_CONTENT = 1;
    const MENU_TYPE_CUSTOM = 2;
}
